/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonCalculator {
        "buttonDisplay": number;
        "classCSS": string;
        "symbol": string;
    }
    interface MyCalculator {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyRow {
    }
    interface ScreenCalculator {
    }
}
declare global {
    interface HTMLButtonCalculatorElement extends Components.ButtonCalculator, HTMLStencilElement {
    }
    var HTMLButtonCalculatorElement: {
        prototype: HTMLButtonCalculatorElement;
        new (): HTMLButtonCalculatorElement;
    };
    interface HTMLMyCalculatorElement extends Components.MyCalculator, HTMLStencilElement {
    }
    var HTMLMyCalculatorElement: {
        prototype: HTMLMyCalculatorElement;
        new (): HTMLMyCalculatorElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyRowElement extends Components.MyRow, HTMLStencilElement {
    }
    var HTMLMyRowElement: {
        prototype: HTMLMyRowElement;
        new (): HTMLMyRowElement;
    };
    interface HTMLScreenCalculatorElement extends Components.ScreenCalculator, HTMLStencilElement {
    }
    var HTMLScreenCalculatorElement: {
        prototype: HTMLScreenCalculatorElement;
        new (): HTMLScreenCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "button-calculator": HTMLButtonCalculatorElement;
        "my-calculator": HTMLMyCalculatorElement;
        "my-component": HTMLMyComponentElement;
        "my-row": HTMLMyRowElement;
        "screen-calculator": HTMLScreenCalculatorElement;
    }
}
declare namespace LocalJSX {
    interface ButtonCalculator {
        "buttonDisplay"?: number;
        "classCSS"?: string;
        "symbol"?: string;
    }
    interface MyCalculator {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyRow {
    }
    interface ScreenCalculator {
    }
    interface IntrinsicElements {
        "button-calculator": ButtonCalculator;
        "my-calculator": MyCalculator;
        "my-component": MyComponent;
        "my-row": MyRow;
        "screen-calculator": ScreenCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-calculator": LocalJSX.ButtonCalculator & JSXBase.HTMLAttributes<HTMLButtonCalculatorElement>;
            "my-calculator": LocalJSX.MyCalculator & JSXBase.HTMLAttributes<HTMLMyCalculatorElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-row": LocalJSX.MyRow & JSXBase.HTMLAttributes<HTMLMyRowElement>;
            "screen-calculator": LocalJSX.ScreenCalculator & JSXBase.HTMLAttributes<HTMLScreenCalculatorElement>;
        }
    }
}
